### ISSUE TITLE
.travis.yml is broken

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#159]
> .travis.yml is missing and builds without .travis.yml are disabled 

https://github.com/travis-ci/travis-ci/issues/2025

probably a syntax error in the config file

**Comment by williballenthin** [comment]
```
~/env/bin/python -m pyaml .travis.yml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/env/lib/python2.7/site-packages/pyaml/__main__.py", line 21, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "/home/user/env/lib/python2.7/site-packages/pyaml/__main__.py", line 15, in main
    try: data = yaml.safe_load(src)
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/user/env/local/lib/python2.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in ".travis.yml", line 30, column 5
expected <block end>, but found '<scalar>'
  in ".travis.yml", line 36, column 9
```

**Comment by williballenthin** [comment]
guess you can't have multiline bash statements in a yaml list. i was surprised when i thought it working. should have trusted my intuition.
