### ISSUE TITLE
Plugins are not installed

### ISSUE THREAD

**Issue by theevilbit** [fireeye/flare-floss#2]
I tried to install this following the guide, but the plugins never got installed. Tried the detailed method as well, but the same happens. The floss/plugins directory is completely missing.

**Comment by theevilbit** [comment]
Tried on Ubuntu and OSX.

**Comment by williballenthin** [comment]
to confirm, when you check the code out via git, the files are present, but when you install the package via pip, they aren't available?

**Comment by williballenthin** [comment]
i think i've reproduced this on a local system. seems we have a silly oversight on the package path handling. should be able to get a fixed version out very soon.

**Comment by williamgibb** [comment]
I have a potentially similar issue w/ plugins when executing a OS X binary built with pyInstaller:
```
nope@nope$ dist/floss
WARNING:__main__.StringDecoderConfig:load_plugins: failed to load extra plugins: The 'floss' distribution was not found and is required by the application
Usage: floss [options] FILEPATH

floss: error: Please provide a valid file path
Try 'floss -h' for more information
```

Adding exception logging shows the following:

```
nope@nope$ python -m floss.main
ERROR:__main__.StringDecoderConfig:
Traceback (most recent call last):
  File "/Users/nope/somepath/flare-floss/floss/main.py", line 156, in load_plugins
    plugins_path = pkg_resources.resource_filename(req, requested_directory)
  File "/usr/local/var/pyenv/versions/2.7.9/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1151, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/local/var/pyenv/versions/2.7.9/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 422, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/var/pyenv/versions/2.7.9/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/var/pyenv/versions/2.7.9/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'floss' distribution was not found and is required by the application
WARNING:__main__.StringDecoderConfig:load_plugins: failed to load extra plugins: The 'floss' distribution was not found and is required by the application
Usage: main.py [options] FILEPATH

main.py: error: Please provide a valid file path
```

@williballenthin  is this related to what you've identified already?

**Comment by williballenthin** [comment]
@williamgibb separate issue. non-fatal error having to do with trying to package dynamically loaded plugins with pyinstaller. let me open a new issue to track this.
