### ISSUE TITLE
UnicodeDecodeError during vivisect loading

### ISSUE THREAD

**Issue by pilate** [fireeye/flare-floss#207]
a28d8ad738e8f3fe413fb493f754d9c0 is throwing this:

```
Traceback (most recent call last):
  File "floss/main.py", line 600, in main
    vw = viv_utils.getWorkspace(sample_file_path, should_save=options.save_workspace)
  File "/usr/local/lib/python2.7/dist-packages/viv_utils-0.3.5-py2.7.egg/viv_utils/__init__.py", line 32, in getWorkspace
    vw.loadFromFile(fp)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/__init__.py", line 2134, in loadFromFile
    fname = mod.parseFile(self, filename)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/parsers/pe.py", line 30, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/parsers/pe.py", line 113, in loadPeIntoWorkspace
    vs = pe.getVS_VERSIONINFO()
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 553, in getVS_VERSIONINFO
    return VS_VERSIONINFO(vbytes)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 161, in __init__
    self._parseBytes(bytes)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 192, in _parseBytes
    offset, vinfosig = self._eatStringAndAlign(bytes, offset)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 224, in _eatStringAndAlign
    return offset, ret.decode('utf-16le')
  File "/usr/lib/python2.7/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 70-71: illegal encoding

```

**Comment by williballenthin** [comment]
looks like bug in vivisect PE parser. do you get a nice message or a stack trace when running in basic mode?

**Comment by pilate** [comment]
Wasn't sure if I should put this on Vivisect or here :)

I do get the cleaner error message but I guess the exception message isn't making it through:

```
ERROR:floss:Vivisect failed to load the input file:
```

**Comment by b0urb0n** [comment]
I'm getting the same error with a WannaCry sample (`5ad4efd90dcde01d26cc6f32f7ce3ce0b4d4951d4b94a19aa097341aff2acaec`):

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib.py", line 15, in get_strings
    vw = get_workspace(path)
  File "lib.py", line 33, in get_workspace
    return load_workspace(path, save_workspace=False)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/floss/main.py", line 935, in load_workspace
    return viv_utils.getWorkspace(sample_file_path, should_save=save_workspace)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/viv_utils/__init__.py", line 43, in getWorkspace
    vw.loadFromFile(fp)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/vivisect/__init__.py", line 2173, in loadFromFile
    fname = mod.parseFile(self, filename)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/vivisect/parsers/pe.py", line 34, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/vivisect/parsers/pe.py", line 116, in loadPeIntoWorkspace
    vs = pe.getVS_VERSIONINFO()
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/PE/__init__.py", line 555, in getVS_VERSIONINFO
    return VS_VERSIONINFO(vbytes)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/PE/__init__.py", line 161, in __init__
    self._parseBytes(bytes)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/PE/__init__.py", line 192, in _parseBytes
    offset, vinfosig = self._eatStringAndAlign(bytes, offset)
  File "/[REDACTED]/venv-legacy/lib/python2.7/site-packages/PE/__init__.py", line 224, in _eatStringAndAlign
    return offset, ret.decode('utf-16le')
  File "/[REDACTED]/venv-legacy/lib/python2.7/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 268-269: illegal UTF-16 surrogate
```

or the CLI version: 
```
$ ~/Downloads/floss --no-static-string 5ad4efd90dcde01d26cc6f32f7ce3ce0b4d4951d4b94a19aa097341aff2acaec
ERROR:floss:Vivisect failed to load the input file:
```

**Comment by mr-tz** [comment]
working in current vivisect/floss:
* a28d8ad738e8f3fe413fb493f754d9c0 
* 5ad4efd90dcde01d26cc6f32f7ce3ce0b4d4951d4b94a19aa097341aff2acaec
