### ISSUE TITLE
SegmentationViolation: Bad Memory Access

### ISSUE THREAD

**Issue by pilate** [fireeye/flare-floss#210]
384e5fa659b1a7550356efb83ba3d7c8

```
ERROR:floss:Vivisect failed to load the input file: Bad Memory Access: 0x41edb8
Traceback (most recent call last):
  File "floss/main.py", line 637, in main
    if not options.quiet:
  File "site-packages/viv_utils/__init__.py", line 33, in getWorkspace
  File "site-packages/vivisect/__init__.py", line 645, in analyze
  File "site-packages/vivisect/__init__.py", line 1117, in makeFunction
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 251, in addCodeFlow
  File "site-packages/envi/codeflow.py", line 270, in addEntryPoint
  File "site-packages/envi/codeflow.py", line 184, in addCodeFlow
  File "site-packages/envi/memory.py", line 157, in readMemoryFormat
  File "site-packages/envi/memory.py", line 439, in readMemory
SegmentationViolation: SegmentationViolation('Bad Memory Access: 0x41edb8',)
```

```
ERROR:floss:Vivisect failed to load the input file: Bad Memory Access: 0x41edb8
```

**Comment by williballenthin** [comment]
vivisect error, need to triage and report upstream

**Comment by mr-tz** [comment]
works in current vivisect/floss
