### ISSUE TITLE
unsupported operand type(s) for &: 'unicode' and 'int'

### ISSUE THREAD

**Issue by pilate** [fireeye/flare-floss#211]
450c065b4f7faec121559511a474c224

```
ERROR:floss:Vivisect failed to load the input file: unsupported operand type(s) for &: 'unicode' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/floss-1.2.0-py2.7.egg/floss/main.py", line 600, in main
    vw = viv_utils.getWorkspace(sample_file_path, should_save=options.save_workspace)
  File "/usr/local/lib/python2.7/dist-packages/viv_utils-0.3.5-py2.7.egg/viv_utils/__init__.py", line 32, in getWorkspace
    vw.loadFromFile(fp)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/__init__.py", line 2134, in loadFromFile
    fname = mod.parseFile(self, filename)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/parsers/pe.py", line 30, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/parsers/pe.py", line 113, in loadPeIntoWorkspace
    vs = pe.getVS_VERSIONINFO()
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 550, in getVS_VERSIONINFO
    vbytes = self.readResource(RT_VERSION, 1)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 513, in readResource
    rsdef = self.getResourceDef(rtype, name_id)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 495, in getResourceDef
    return self.ResourceRoot.getResourceDef(rtype, name_id)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 1079, in __getattr__
    self.parseResources()
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/PE/__init__.py", line 618, in parseResources
    langid = name_id & 0x3ff
TypeError: unsupported operand type(s) for &: 'unicode' and 'int'
```

```
ERROR:floss:Vivisect failed to load the input file: unsupported operand type(s) for &: 'unicode' and 'int'

```

**Comment by mr-tz** [comment]
works in current vivisect/floss
