### ISSUE TITLE
unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by pilate** [fireeye/flare-floss#215]
f5aa018daa34809da455a86336f23331

```
Traceback (most recent call last):
  File "floss/main.py", line 600, in main
    vw = viv_utils.getWorkspace(sample_file_path, should_save=options.save_workspace)
  File "/usr/local/lib/python2.7/dist-packages/viv_utils-0.3.5-py2.7.egg/viv_utils/__init__.py", line 33, in getWorkspace
    vw.analyze()
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/__init__.py", line 645, in analyze
    self.makeFunction(eva)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/__init__.py", line 1117, in makeFunction
    self.cfctx.addEntryPoint(va, arch=arch)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/envi/codeflow.py", line 270, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/envi/codeflow.py", line 166, in addCodeFlow
    branches = self._cb_opcode(va, op, branches)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/base.py", line 639, in _cb_opcode
    self._mem.makeOpcode(op.va, op=op)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/__init__.py", line 1032, in makeOpcode
    val = self.parseNumber(ref, o.tsize)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/vivisect/__init__.py", line 1633, in parseNumber
    return e_bits.parsebytes(bytes, offset, size, bigend=self.bigend)
  File "/usr/local/lib/python2.7/dist-packages/vivisect-0.0.0-py2.7.egg/envi/bits.py", line 155, in parsebytes
    x = struct.unpack(f, d)[0]
error: unpack requires a string argument of length 4
```

```
ERROR:floss:Vivisect failed to load the input file: unpack requires a string argument of length 4
```

**Comment by mr-tz** [comment]
now getting:
`ERROR:floss:Vivisect failed to load the input file: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte`

**Comment by mr-tz** [comment]
reported upstream at https://github.com/vivisect/vivisect/issues/509

**Comment by mr-tz** [comment]
fixed upstream
