### ISSUE TITLE
Vivisect problem - there is not constants module at vstruct

### ISSUE THREAD

**Issue by alexandreborges** [fireeye/flare-floss#274]
Willi,

Good morning. How are you?

I've tried to use the **stackstrings plugin** (from flare-ida) in my IDA Pro (6.95 - Windows), but I've faced problems with the **vivisect**. Therefore, I have realized that I would also have problems to install Floss using pip.  

Eventually, you should to update the vivisect's base.py because it is complaining about the constants modules:

```
C:\Users\AB> **python**
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> **import vivisect**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\vivisect\__init__.py", line 42, in <module>
    import vivisect.base as viv_base
  File "c:\python27\lib\site-packages\vivisect\base.py", line 13, in <module>
    import vstruct.constants as vs_const
**ImportError: No module named constants**
```

Indeed, there is not any constants module at `vstruct\constants`, as shown below:

```
C:\Python27\Lib\site-packages\vstruct\constants>dir

 Directory of C:\Python27\Lib\site-packages\vstruct\constants

09/15/2017  04:32 AM    <DIR>          .
09/15/2017  04:32 AM    <DIR>          ..
09/15/2017  04:31 AM            46,956 ntstatus.py
09/15/2017  04:32 AM            58,104 ntstatus.pyc
09/15/2017  04:31 AM               939 __init__.py
09/15/2017  04:32 AM             1,707 __init__.pyc
               4 File(s)        107,706 bytes
               2 Dir(s)  17,719,386,112 bytes free
```

As usual, I've followed the suggested steps:

step 1.  **pip install https://github.com/williballenthin/vivisect/zipball/master**
step 2.  **pip install https://github.com/fireeye/flare-floss/zipball/master**

Additionally, I have also installed the constants package (pip install constants) and changed the base.py, but there are other small problems. 

Personally, I could download the binary version of Floss, but there could be a problem not having a working version of vivisect package because **stackstrings plugin.** 

I hope you have an amazing day and thank you for your usual help. 

Alexandre.

**Comment by williballenthin** [comment]
I cannot reproduce this issue:

```
localhost:~ $ cd /tmp
localhost:/tmp $ mkdir a
localhost:/tmp $ virtualenv -p python2 a 
Already using interpreter /usr/bin/python2
New python executable in /tmp/a/bin/python2
Also creating executable in /tmp/a/bin/python
Installing setuptools, pip, wheel...done.
localhost:/tmp $ cd a
localhost:a $ ./bin/pip install https://github.com/williballenthin/vivisect/zipball/master 
Collecting https://github.com/williballenthin/vivisect/zipball/master
  Downloading https://github.com/williballenthin/vivisect/zipball/master (3.6MB)
    100% |████████████████████████████████| 3.6MB 46kB/s 
Collecting pycparser (from vivisect==0.0.20170525)
  Using cached pycparser-2.18.tar.gz
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/user/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built pycparser
Installing collected packages: pycparser, vivisect
  Running setup.py install for vivisect ... done
Successfully installed pycparser-2.18 vivisect-0.0.20170525
localhost:a $ ./bin/pip install https://github.com/fireeye/flare-floss/zipball/master
Collecting https://github.com/fireeye/flare-floss/zipball/master
  Downloading https://github.com/fireeye/flare-floss/zipball/master
     | 153kB 26kB/s
Collecting q (from floss==1.5.0)
  Downloading q-2.6-py2.py3-none-any.whl
Collecting pyyaml (from floss==1.5.0)
Collecting tabulate (from floss==1.5.0)
  Using cached tabulate-0.7.7-py2.py3-none-any.whl
Requirement already satisfied: vivisect in ./lib/python2.7/site-packages (from floss==1.5.0)
Collecting plugnplay (from floss==1.5.0)
  Downloading plugnplay-0.5.3.tar.gz
Collecting viv-utils (from floss==1.5.0)
  Downloading viv_utils-0.3.7-py2-none-any.whl
Collecting enum34 (from floss==1.5.0)
  Using cached enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: pycparser in ./lib/python2.7/site-packages (from vivisect->floss==1.5.0)
Collecting argparse (from viv-utils->floss==1.5.0)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting funcy (from viv-utils->floss==1.5.0)
  Downloading funcy-1.9.tar.gz
Collecting intervaltree (from viv-utils->floss==1.5.0)
  Downloading intervaltree-2.1.0.tar.gz
Collecting pefile (from viv-utils->floss==1.5.0)
  Downloading pefile-2017.9.3.tar.gz (61kB)
    100% |████████████████████████████████| 71kB 49kB/s 
Collecting sortedcontainers (from intervaltree->viv-utils->floss==1.5.0)
  Downloading sortedcontainers-1.5.7-py2.py3-none-any.whl
Collecting future (from pefile->viv-utils->floss==1.5.0)
Building wheels for collected packages: plugnplay, funcy, intervaltree, pefile
  Running setup.py bdist_wheel for plugnplay ... done
  Stored in directory: /home/user/.cache/pip/wheels/ed/50/f6/f9568f8ef819e2125335604ba6ba7086d5a618f220f5581176
  Running setup.py bdist_wheel for funcy ... done
  Stored in directory: /home/user/.cache/pip/wheels/61/06/f9/2ac5b0438a90f0ab0b241307daac6fe5d7bdd799516c659d5f
  Running setup.py bdist_wheel for intervaltree ... done
  Stored in directory: /home/user/.cache/pip/wheels/89/40/01/fa05b5a8202a472fb143815e7589fdf74369e710ca675cad11
  Running setup.py bdist_wheel for pefile ... done
  Stored in directory: /home/user/.cache/pip/wheels/39/0c/14/d8c07e18085e20f3050f1e3f6c6343f640e0fbc498957be227
Successfully built plugnplay funcy intervaltree pefile
Installing collected packages: q, pyyaml, tabulate, plugnplay, argparse, funcy, sortedcontainers, intervaltree, future, pefile, viv-utils, enum34, floss
  Running setup.py install for floss ... done
Successfully installed argparse-1.4.0 enum34-1.1.6 floss-1.5.0 funcy-1.9 future-0.16.0 intervaltree-2.1.0 pefile-2017.9.3 plugnplay-0.5.3 pyyaml-3.12 q-2.6 sortedcontainers-1.5.7 tabulate-0.7.7 viv-utils-0.3.7
localhost:a $ ./bin/python 
Python 2.7.13 (default, Jun 26 2017, 10:20:05) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vivisect
>>> 
```

**Comment by williballenthin** [comment]
cannot reproduce on windows, either:

```
C:\Users\user\Desktop>mkdir a

C:\Users\user\Desktop>C:\Python27\Scripts\virtualenv.exe  a
New python executable in C:\Users\user\Desktop\a\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Users\user\Desktop>pip install https://github.com/williballenthin/vivisect/zipball/master
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user\Desktop>cd a

C:\Users\user\Desktop\a>Scripts\pip install https://github.com/williballenthin/vivisect/zipball/master
Collecting https://github.com/williballenthin/vivisect/zipball/master
  Downloading https://github.com/williballenthin/vivisect/zipball/master (3.6MB)
    100% |################################| 3.6MB 102kB/s
Collecting pycparser (from vivisect==0.0.20170525)
Installing collected packages: pycparser, vivisect
  Running setup.py install for vivisect ... done
Successfully installed pycparser-2.18 vivisect-0.0.20170525
C:\Users\user\Desktop\a>Scripts\pip install https://github.com/williballenthin/vivisect/zipball/master
Collecting https://github.com/williballenthin/vivisect/zipball/master
  Downloading https://github.com/williballenthin/vivisect/zipball/master (3.6MB)
    100% |################################| 3.6MB 242kB/s
  Requirement already satisfied (use --upgrade to upgrade): vivisect==0.0.20170525 from https://github.com/williballenthin/vivisect/zipball/master in c:\users\user\desktop\a\lib\site-packages
Requirement already satisfied: pycparser in c:\users\user\desktop\a\lib\site-packages (from vivisect==0.0.20170525)

C:\Users\user\Desktop\a>Scripts\python.exe
Python 2.7.12 | packaged by conda-forge | (default, Sep  8 2016, 14:45:16) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vivisect
>>>
```

**Comment by williballenthin** [comment]
you'll need to provide a more specific test case demonstrating the issue, because right now i'm not able to identify it.

please re-open this issue when you have collected this information.

**Comment by williballenthin** [comment]
this is possibly due to a bug with the `vivisect-vstruct-wb` package i publish. it seems to not contain the `vstruct.constants` module:

```
localhost:/tmp $ cp /usr/lib/python2.7/site-packages/vivisect_vstruct_wb-1.0.3-py2.7.egg .
localhost:/tmp $ unzip vivisect_vstruct_wb-1.0.3-py2.7.egg 
Archive:  vivisect_vstruct_wb-1.0.3-py2.7.egg
  inflating: EGG-INFO/zip-safe       
  inflating: EGG-INFO/top_level.txt  
  inflating: EGG-INFO/dependency_links.txt  
  inflating: EGG-INFO/SOURCES.txt    
  inflating: EGG-INFO/PKG-INFO       
  inflating: vstruct/cparse.pyc      
  inflating: vstruct/builder.pyc     
  inflating: vstruct/__init__.pyc    
  inflating: vstruct/bitfield.pyc    
  inflating: vstruct/primitives.pyc  
  inflating: vstruct/cparse.py       
  inflating: vstruct/builder.py      
  inflating: vstruct/__init__.py     
  inflating: vstruct/bitfield.py     
  inflating: vstruct/primitives.py   
```

**Comment by williballenthin** [comment]
reported here https://github.com/fireeye/flare-floss/issues/274

**Comment by alexandreborges** [comment]
Willi,

Good morning. How are you?

Thank you for the attention and time for analyzing it.

Actually, this is exactly my problem. However, as I have mentioned to you, I have noticed this problem while using **stringstack.py IDA plugin** because it uses **vivisect** as shown below:

**try:
import vivisect
import envi.bits as e_bits
from visgraph import pathcore as vg_path
except Exception, err:
print 'Error importing stuff!'
raise**

I hope you have an amazing day, Willi.

Alexandre.
