### ISSUE TITLE
ImportError: cannot import name 'ONE_MB'

### ISSUE THREAD

**Issue by Bhuvanamitra** [fireeye/flare-floss#308]
I have downloaded standard library for Linux from here:
(https://github.com/fireeye/flare-floss/releases)
When I try to run on my linux machine, It has asked for some missing libraries like tabulate, q, funcy etc and I have installed them.
Now when I run floss <malware.exe>, it gives me this error:

Traceback (most recent call last):
  File "/home/local/ZOHOCORP/bhuvan-3031/anaconda2/bin/floss", line 11, in <module>
    load_entry_point('floss==1.5.1', 'console_scripts', 'floss')()
  File "/home/local/ZOHOCORP/bhuvan-3031/anaconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/local/ZOHOCORP/bhuvan-3031/anaconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/local/ZOHOCORP/bhuvan-3031/anaconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/local/ZOHOCORP/bhuvan-3031/anaconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/local/ZOHOCORP/bhuvan-3031/anaconda2/lib/python3.6/site-packages/floss-1.5.1-py3.6.egg/floss/__init__.py", line 3, in <module>
    from utils import ONE_MB
ImportError: cannot import name 'ONE_MB'

Can Someone please help me in resolving this and tell how to run floss successfully?

**Comment by Cyber00011011** [comment]
I have this same error on a Windows 10 x64 system. Was there a fix for this error?  "cannot import name 'ONE_MB' from utils"

**Comment by williballenthin** [comment]
FLOSS runs on py2. Are you running under py2 or py3?
