### ISSUE TITLE
Fresh install: Syntax error in strings.py 

### ISSUE THREAD

**Issue by MitchHS** [fireeye/flare-floss#349]
I'm trying to do an offline install for floss. I downloaded all the dependencies via pip download. After running `python setup.py install` the installation passes fine, but when I try to run floss via the cmdline I receive the error:

```Traceback (most recent call last):
  File "/usr/local/bin/floss", line 11, in <module>
    load_entry_point('floss==1.6.1', 'console_scripts', 'floss')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/floss-1.6.1-py2.7.egg/floss/main.py", line 21, in <module>
    import floss.strings as strings
  File "/usr/local/lib/python2.7/dist-packages/floss-1.6.1-py2.7.egg/floss/strings.py", line 6
    ASCII_BYTE = rb"!\"#\$%&\'\(\)\*\+,-\./0123456789:;<=>\?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\[\]\^_`abcdefghijklmnopqrstuvwxyz\{\|\}\\\~\t"

SyntaxError : invalid syntax
```

Running on Ubuntu GNU/Linux, python2 2.7.17

**Comment by mr-tz** [comment]
Sorry for the issue. This should be fixed now.

**Comment by MitchHS** [comment]
No worries - Figured I should bring that to your attention. 

Cheers!
