### ISSUE TITLE
LookupError: unknown encoding: cp65001

### ISSUE THREAD

**Issue by evild3ad** [fireeye/flare-floss#375]
```
.\floss.exe -h

Traceback (most recent call last):
  File "floss\main.py", line 1247, in <module>
  File "floss\main.py", line 1097, in main
  File "optparse.py", line 1400, in parse_args
  File "optparse.py", line 1444, in _process_args
  File "optparse.py", line 1551, in _process_short_opts
  File "optparse.py", line 789, in process
  File "optparse.py", line 811, in take_action
  File "optparse.py", line 1670, in print_help
LookupError: unknown encoding: cp65001
[19144] Failed to execute script main
```

The standalone executable is not working in any console on my Windows system. 

I tried to change the output encoding in PowerShell, but I still get the same error message.
`[Console]::OutputEncoding = [System.Text.Encoding]::Default`

Is there a workaround or can you fix it with your next release?

Thank you!

**Comment by williballenthin** [comment]
good catch! we'll fix this in our next release.

i think we need to port over this logic from capa that's relevant on py3.8+:

https://github.com/fireeye/capa/blob/94485285f379bc22ba9a9601988d0b3563884fc0/capa/main.py#L707-L712
