### ISSUE TITLE
Argv handling Error 

### ISSUE THREAD

**Issue by Harri-Renney** [fireeye/flare-floss#407]
Getting the following error with the latest commit:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/floss", line 33, in <module>
    sys.exit(load_entry_point('flare-floss', 'console_scripts', 'floss')())
  File "/home/user/FLOSS/flare-floss/floss/main.py", line 602, in main
    parser = make_parser(argv[1:] or sys.argv[1:])
TypeError: 'NoneType' object is not subscriptable
```

Reverting back to changes made before commit 9dc1b298c1e3ccaa5d30e923496fe4281c83ca50 where main.py lines 602 & 603 were:

```
parser = make_parser(argv or sys.argv[1:])
args = parser.parse_args(args=argv)
```

Fixed this for me.

**Comment by williballenthin** [comment]
ah, good catch, thanks

**Comment by williballenthin** [comment]
should be fixed - let me know if you encounter any further exceptions
